openapi: 3.2.0
info:
  title: Equipment Vendor API (for standalone clients) Partners API
  description: At EGYM, we believe that fitness is the soul of healthy living.
  termsOfService: https://egym.com/us/terms/
  contact:
    name: EGYM GmbH
    url: https://egym.com/
    email: support@egym.com
  license:
    name: Pending License
    url: https://egym.com/
  version: 1.2.0
servers:
- url: https://partner-api.ext-1.test.co.egym.coffee
  description: Test (ext-1)
- url: https://partner-api.api.egym.com
  description: Production
tags:
- name: Partners
paths:
  /api/v1/partners/info:
    get:
      tags:
      - Partners
      summary: info
      description: This endpoint returns the partner information which is related to the given credentials, if these credentials are invalid it will return a HTTP 401 UNAUTHORIZED error code.
      operationId: info
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerInfoDTO'
        '401':
          description: Unauthorized
      security:
      - partner: []
components:
  schemas:
    PartnerInfoDTO:
      type: object
      properties:
        name:
          type: string
          description: The partner name.
        createdAt:
          type: integer
          format: int64
          description: The date of creation.
          example: 1672531200000
        featureFlags:
          type: array
          description: The feature flags enabled for this gym.
          items:
            type: string
  securitySchemes:
    user:
      type: http
      scheme: bearer
      bearerFormat: JWT
    partner:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /api/v1/oauth/token
          scopes: {}
x-tagGroups:
- name: Authentication
  tags:
  - OAuth
- name: Partners Information
  tags:
  - Partners
- name: Measurements
  tags:
  - Body Measurement
  - Cardio Measurement
  - Flexibility Measurement
- name: User
  tags:
  - User
  - Image
  - Statistics
- name: Machine
  tags:
  - Machine
- name: Resource
  tags:
  - Resource
- name: Workouts
  tags:
  - Strength Workouts
  - Cardio Workouts
  - Open Exercise Workouts
- name: Cardio Test
  tags:
  - Cardio Test
- name: Logging
  tags:
  - Logging
